<template>
  <section v-if="spots.length" id="nearby" class="content-section card spot-detail-nearby">
    <h2>In der Nähe</h2>
    <div class="nearby-viewport">
      <button
        v-show="canScrollLeft"
        type="button"
        class="nearby-arrow nearby-arrow-prev"
        aria-label="Vorherige"
        @click="page(-1)"
      >
        <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M15 5l-7 7 7 7" /></svg>
      </button>

      <ul ref="trackEl" class="nearby-track" @scroll="updateArrows">
        <li v-for="s in spots" :key="s.id" class="nearby-item">
          <NuxtLink :to="`/trails/${s.id}`" class="nearby-card">
            <img
              :src="s.photo || FALLBACK_IMG"
              loading="lazy"
              alt=""
              class="nearby-thumb"
              :class="{ 'is-fallback': !s.photo }"
            />
            <span class="nearby-body">
              <span class="nearby-name">{{ s.name }}</span>
              <span class="nearby-meta">
                <span class="nearby-type-dot" :style="{ background: typeColor(s.type) }"></span>
                {{ typeLabel(s.type) }} · {{ formatKm(s.km) }} entfernt
              </span>
            </span>
          </NuxtLink>
        </li>
      </ul>

      <button
        v-show="canScrollRight"
        type="button"
        class="nearby-arrow nearby-arrow-next"
        aria-label="Weitere"
        @click="page(1)"
      >
        <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M9 5l7 7-7 7" /></svg>
      </button>
    </div>
  </section>
</template>

<script setup lang="ts">
import type { NearbySpot, SpotType } from '@@/build/nearby'

// Build-time list of the closest other spots, rendered at the bottom of the
// trails/[slug] detail page as a horizontal carousel: swipe on touch, arrow
// buttons on pointer devices (shown only when the row actually overflows).
// Data comes from public/nearby.json (generated by the nitro:config hook in
// nuxt.config.ts → build/nearby.ts); the page fetches it and passes this
// component the slice for the current spot.
const props = defineProps<{ spots: NearbySpot[] }>()

// Branded stand-in for spots that have no community photo yet — a small webp
// derived from assets/splash.png (public/assets/nearby-fallback.webp).
const FALLBACK_IMG = '/assets/nearby-fallback.webp'

const trackEl = ref<HTMLElement | null>(null)
const canScrollLeft = ref(false)
const canScrollRight = ref(false)

function updateArrows() {
  const el = trackEl.value
  if (!el) return
  canScrollLeft.value = el.scrollLeft > 4
  canScrollRight.value = el.scrollLeft + el.clientWidth < el.scrollWidth - 4
}

function page(dir: number) {
  const el = trackEl.value
  if (!el) return
  // Manual rAF scroll: scrollBy({ behavior: 'smooth' }) is silently dropped
  // inside a scroll-snap container in Chrome; direct scrollLeft assignment works.
  const from = el.scrollLeft
  const to = from + dir * el.clientWidth * 0.9
  const startedAt = performance.now()
  const duration = 300
  function frame(now: number) {
    const p = Math.min(1, (now - startedAt) / duration)
    const eased = p < 0.5 ? 2 * p * p : 1 - Math.pow(-2 * p + 2, 2) / 2
    el!.scrollLeft = from + (to - from) * eased
    if (p < 1) requestAnimationFrame(frame)
  }
  requestAnimationFrame(frame)
}

onMounted(() => {
  updateArrows()
  window.addEventListener('resize', updateArrows)
})
onUnmounted(() => window.removeEventListener('resize', updateArrows))
watch(() => props.spots, () => nextTick(updateArrows))

// Matches the map marker palette in app/assets/css/marker.css.
const TYPE_COLOR: Record<SpotType, string> = {
  trail: '#3b82f6',
  bikepark: '#10b981',
  dirtpark: '#b91794',
}
const TYPE_LABEL: Record<SpotType, string> = {
  trail: 'Trail',
  bikepark: 'Bikepark',
  dirtpark: 'Dirtpark',
}

function typeColor(t: SpotType): string {
  return TYPE_COLOR[t] ?? '#8a96a8'
}
function typeLabel(t: SpotType): string {
  return TYPE_LABEL[t] ?? 'Spot'
}
function formatKm(km: number): string {
  return `${km.toLocaleString('de-DE', { maximumFractionDigits: 1 })} km`
}
</script>

<style scoped>
.nearby-viewport {
  position: relative;
  /* Square thumbnail edge length — the row scrolls one "page" (~90% of the
     visible width) per arrow click. */
  --nearby-thumb: clamp(170px, 46vw, 240px);
}

.nearby-track {
  list-style: none;
  margin: 0;
  padding: 0.2em 0 0.5em;
  display: flex;
  gap: 1em;
  overflow-x: auto;
  /* `proximity`, not `mandatory`: mandatory re-snaps every frame and cancels
     the arrow buttons' smooth scrollBy(); proximity still snaps on release. */
  scroll-snap-type: x proximity;
  -webkit-overflow-scrolling: touch;
  scrollbar-width: none;
}
.nearby-track::-webkit-scrollbar { display: none; }

.nearby-item {
  flex: 0 0 auto;
  width: var(--nearby-thumb);
  scroll-snap-align: start;
}

.nearby-card {
  display: flex;
  flex-direction: column;
  gap: 0.6em;
  text-decoration: none;
  color: inherit;
}

.nearby-thumb {
  width: 100%;
  aspect-ratio: 1 / 1;
  border-radius: 14px;
  object-fit: cover;
  border: 1px solid #e4e9f0;
  background: #f0faf5;
  transition: transform 0.15s;
}
.nearby-card:hover .nearby-thumb {
  transform: translateY(-2px);
}
/* The branded fallback tile is busier than a real photo — sink it back a touch. */
.nearby-thumb.is-fallback {
  background: #1a2035;
  border-color: #1a2035;
}

.nearby-body {
  display: flex;
  flex-direction: column;
  gap: 0.2em;
  min-width: 0;
}

.nearby-name {
  font-size: 0.9em;
  font-weight: 700;
  color: #1a2035;
  line-height: 1.25;
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}

.nearby-meta {
  display: flex;
  align-items: center;
  gap: 0.4em;
  font-size: 0.76em;
  color: #8a96a8;
}

.nearby-type-dot {
  width: 8px;
  height: 8px;
  border-radius: 50%;
  flex-shrink: 0;
}

.nearby-arrow {
  position: absolute;
  top: calc(var(--nearby-thumb) / 2 + 0.2em);
  transform: translateY(-50%);
  z-index: 2;
  width: 38px;
  height: 38px;
  display: none;
  align-items: center;
  justify-content: center;
  padding: 0;
  border: 1px solid #e4e9f0;
  border-radius: 50%;
  background: #fff;
  color: #1a2035;
  cursor: pointer;
  box-shadow: 0 2px 12px rgba(0, 0, 0, 0.14);
  transition: background 0.15s, color 0.15s;
}
.nearby-arrow svg {
  width: 18px;
  height: 18px;
  fill: none;
  stroke: currentColor;
  stroke-width: 2.5;
  stroke-linecap: round;
  stroke-linejoin: round;
}
.nearby-arrow:hover {
  background: #1a2035;
  color: #fff;
}
.nearby-arrow-prev { left: -0.4em; }
.nearby-arrow-next { right: -0.4em; }

/* Arrows are a pointer-device affordance; touch users swipe. */
@media (hover: hover) and (pointer: fine) {
  .nearby-arrow { display: flex; }
}
</style>
