import { describe, it, expect, beforeEach } from 'vitest'
import { PGlite } from '@electric-sql/pglite'
import { readFileSync, readdirSync } from 'node:fs'
import { join } from 'node:path'
import { anon } from '../anon'

// Behavioural RLS check: runs the real trail_photos migrations in an in-process
// Postgres (PGlite) on top of a minimal stub of Supabase's auth/storage schemas.
// Never touches the production database.

const MIGRATIONS = join(process.cwd(), 'supabase', 'migrations')
const migration = (suffix: string) => {
  const file = readdirSync(MIGRATIONS).find(f => f.endsWith(suffix))
  if (!file) throw new Error(`missing migration *${suffix}`)
  return readFileSync(join(MIGRATIONS, file), 'utf8')
}

const ALICE = '00000000-0000-0000-0000-00000000000a'
const BOB = '00000000-0000-0000-0000-00000000000b'
const TRAIL = 'trail-1'
// The production host the app ships with, from the anon key's `ref` claim — pins the
// migration's allowlist to the real project without hardcoding its id here.
const PROJECT_REF = JSON.parse(Buffer.from(anon.split('.')[1]!, 'base64url').toString()).ref as string
const BASE = `https://${PROJECT_REF}.supabase.co/storage/v1/object/public/trail-photos/`
const LOCAL_BASE = 'http://127.0.0.1:54321/storage/v1/object/public/trail-photos/'

// Mirrors the parts of Supabase + 20260514075528_remote_schema.sql these rules depend on.
const SUPABASE_STUB = `
  CREATE ROLE anon NOLOGIN;
  CREATE ROLE authenticated NOLOGIN;
  CREATE SCHEMA auth;
  CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS
    $$ SELECT nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
  GRANT USAGE ON SCHEMA auth TO anon, authenticated;

  CREATE SCHEMA storage;
  CREATE TABLE storage.objects (bucket_id text, name text, owner uuid, owner_id text);
  CREATE FUNCTION storage.foldername(name text) RETURNS text[] LANGUAGE sql IMMUTABLE AS
    $$ SELECT (string_to_array(name, '/'))[1:array_length(string_to_array(name, '/'), 1) - 1] $$;
  -- RLS on with no SELECT policy: clients cannot read object rows directly.
  ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;
  GRANT USAGE ON SCHEMA storage TO anon, authenticated;
  GRANT ALL ON storage.objects TO anon, authenticated;

  CREATE FUNCTION public.can_edit_spot(spot_id text) RETURNS boolean LANGUAGE sql AS $$ SELECT false $$;

  CREATE TABLE public.trail_photos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz DEFAULT now() NOT NULL,
    trail_id text, url text, creator uuid
  );
  CREATE POLICY "get" ON public.trail_photos FOR SELECT TO anon USING (true);
  CREATE POLICY "insert" ON public.trail_photos FOR INSERT TO authenticated WITH CHECK (true);
  ALTER TABLE public.trail_photos ENABLE ROW LEVEL SECURITY;
  GRANT ALL ON TABLE public.trail_photos TO anon, authenticated;
`

let db: PGlite

async function as(user: string | null, sql: string, params: unknown[] = []) {
  await db.exec(`RESET ROLE; SELECT set_config('request.jwt.claim.sub', '${user ?? ''}', false);`)
  await db.exec(`SET ROLE ${user ? 'authenticated' : 'anon'}`)
  try {
    return await db.query<Record<string, unknown>>(sql, params)
  } finally {
    await db.exec('RESET ROLE')
  }
}

// What Supabase Storage records when `user` uploads `name` into trail-photos.
async function uploaded(user: string, name: string) {
  await db.query(`INSERT INTO storage.objects VALUES ('trail-photos', $1, $2::uuid, $3)`, [name, user, user])
}

const insertPhoto = (user: string | null, row: { trail_id: string; url: string; creator: string | null; copyright?: string | null }) =>
  as(user, 'INSERT INTO public.trail_photos (trail_id, url, creator, copyright) VALUES ($1, $2, $3, $4)',
    [row.trail_id, row.url, row.creator, row.copyright ?? null])

beforeEach(async () => {
  db = new PGlite()
  await db.exec(SUPABASE_STUB)
  await db.exec(migration('_add_trail_photo_delete_policies.sql'))
  await db.exec(migration('_fix_trail_photo_delete_returning.sql'))
  await db.exec(migration('_add_trail_photo_copyright.sql'))
  await db.exec(migration('_restrict_trail_photo_insert.sql'))
})

describe('trail_photos INSERT', () => {
  it('accepts the app upload flow: own user, own freshly uploaded file, matching trail', async () => {
    await uploaded(ALICE, `${TRAIL}/a.webp`)
    await insertPhoto(ALICE, { trail_id: TRAIL, url: `${BASE}${TRAIL}/a.webp`, creator: ALICE, copyright: 'Alice' })

    const { rows } = await db.query('SELECT creator, copyright FROM public.trail_photos')
    expect(rows).toEqual([{ creator: ALICE, copyright: 'Alice' }])
  })

  it('accepts uploads against a local Supabase (supabase start)', async () => {
    await uploaded(ALICE, `${TRAIL}/a.webp`)
    await insertPhoto(ALICE, { trail_id: TRAIL, url: `${LOCAL_BASE}${TRAIL}/a.webp`, creator: ALICE })
    expect((await db.query('SELECT 1 FROM public.trail_photos')).rows).toHaveLength(1)
  })

  it('rejects a row attributed to another user', async () => {
    await uploaded(BOB, `${TRAIL}/b.webp`)
    await expect(insertPhoto(BOB, { trail_id: TRAIL, url: `${BASE}${TRAIL}/b.webp`, creator: ALICE }))
      .rejects.toThrow(/row-level security/)
  })

  it("rejects reusing someone else's uploaded file under your own copyright", async () => {
    await uploaded(ALICE, `${TRAIL}/a.webp`)
    await expect(insertPhoto(BOB, { trail_id: TRAIL, url: `${BASE}${TRAIL}/a.webp`, creator: BOB, copyright: 'Bob' }))
      .rejects.toThrow(/row-level security/)
  })

  it('rejects a URL on a foreign host, even if the path matches an own file', async () => {
    await uploaded(BOB, `${TRAIL}/b.webp`)
    await expect(insertPhoto(BOB, { trail_id: TRAIL, url: `https://evil.example/storage/v1/object/public/trail-photos/${TRAIL}/b.webp`, creator: BOB }))
      .rejects.toThrow(/row-level security/)
  })

  it("rejects attaching a file to a trail other than the one it was uploaded under", async () => {
    await uploaded(BOB, `${TRAIL}/b.webp`)
    await expect(insertPhoto(BOB, { trail_id: 'trail-2', url: `${BASE}${TRAIL}/b.webp`, creator: BOB }))
      .rejects.toThrow(/row-level security/)
  })

  it('rejects a second row for the same file', async () => {
    await uploaded(ALICE, `${TRAIL}/a.webp`)
    await insertPhoto(ALICE, { trail_id: TRAIL, url: `${BASE}${TRAIL}/a.webp`, creator: ALICE })
    await expect(insertPhoto(ALICE, { trail_id: TRAIL, url: `${BASE}${TRAIL}/a.webp`, creator: ALICE, copyright: 'x' }))
      .rejects.toThrow(/duplicate key|unique/)
  })

  it('rejects inserts from anonymous visitors', async () => {
    await uploaded(ALICE, `${TRAIL}/a.webp`)
    await expect(insertPhoto(null, { trail_id: TRAIL, url: `${BASE}${TRAIL}/a.webp`, creator: ALICE }))
      .rejects.toThrow()
  })

  it('rejects a copyright longer than 100 characters', async () => {
    await uploaded(ALICE, `${TRAIL}/a.webp`)
    await expect(insertPhoto(ALICE, { trail_id: TRAIL, url: `${BASE}${TRAIL}/a.webp`, creator: ALICE, copyright: 'x'.repeat(101) }))
      .rejects.toThrow(/copyright_length/)
  })
})

describe('trail_photos UPDATE', () => {
  beforeEach(async () => {
    await uploaded(ALICE, `${TRAIL}/a.webp`)
    await insertPhoto(ALICE, { trail_id: TRAIL, url: `${BASE}${TRAIL}/a.webp`, creator: ALICE })
  })

  const copyright = async () => (await db.query<{ copyright: string | null }>('SELECT copyright FROM public.trail_photos')).rows[0]!.copyright

  it('lets the uploader set the copyright', async () => {
    const { rows } = await as(ALICE, `UPDATE public.trail_photos SET copyright = 'Alice' RETURNING id`)
    expect(rows).toHaveLength(1)
    expect(await copyright()).toBe('Alice')
  })

  it("silently matches zero rows for another user's photo", async () => {
    const { rows } = await as(BOB, `UPDATE public.trail_photos SET copyright = 'Bob' RETURNING id`)
    expect(rows).toHaveLength(0)
    expect(await copyright()).toBeNull()
  })

  it('denies anonymous visitors', async () => {
    await expect(as(null, `UPDATE public.trail_photos SET copyright = 'x'`)).rejects.toThrow(/permission denied/)
  })

  it.each(['url', 'creator', 'trail_id'])('denies the uploader changing %s', async (column) => {
    await expect(as(ALICE, `UPDATE public.trail_photos SET ${column} = ${column}`)).rejects.toThrow(/permission denied/)
  })
})
