


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "hypopg" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "index_advisor" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "moddatetime" WITH SCHEMA "public";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE TYPE "public"."user_role" AS ENUM (
    'admin',
    'trailcrew',
    'user'
);


ALTER TYPE "public"."user_role" OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."can_edit_spot"("p_spot_id" "text") RETURNS boolean
    LANGUAGE "sql" STABLE SECURITY DEFINER
    AS $$SELECT is_admin()
OR (get_my_role() = 'trailcrew'                                                                   AND EXISTS (        
            SELECT 1 FROM trailcrew_spots                  
            WHERE user_id = auth.uid() AND spot_id::text = p_spot_id ))$$;


ALTER FUNCTION "public"."can_edit_spot"("p_spot_id" "text") OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."get_my_role"() RETURNS "public"."user_role"
    LANGUAGE "sql" STABLE SECURITY DEFINER
    AS $$SELECT COALESCE(
      (SELECT role FROM user_roles WHERE user_id = auth.uid()),                                                                                                                                                                         
      'user'::user_role
    )$$;


ALTER FUNCTION "public"."get_my_role"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."is_admin"() RETURNS boolean
    LANGUAGE "sql" STABLE SECURITY DEFINER
    AS $$SELECT get_my_role() = 'admin'$$;


ALTER FUNCTION "public"."is_admin"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."sync_profile_from_auth_users"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$BEGIN
  -- On INSERT or UPDATE of auth.users, upsert into public.profiles
  INSERT INTO public.profiles (id, display_name, avatar_url, created_at)
  VALUES (
    NEW.id,
    (NEW.raw_user_meta_data ->> 'name')::text,
    (NEW.raw_user_meta_data ->> 'avatar_url')::text,
    NEW.created_at
  )
  ON CONFLICT (id) DO UPDATE
  SET
    display_name = EXCLUDED.display_name,
    avatar_url = EXCLUDED.avatar_url,
    created_at = EXCLUDED.created_at;

  RETURN NEW;
END;$$;


ALTER FUNCTION "public"."sync_profile_from_auth_users"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."add_entry_aborts" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."add_entry_aborts" OWNER TO "postgres";


ALTER TABLE "public"."add_entry_aborts" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."add_entry_aborts_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."bike_park_details" (
    "id" "text" NOT NULL,
    "status" "text",
    "status_hint" "text",
    "opening_hours" "text",
    "rules" "jsonb",
    "trails_descriptions" "jsonb",
    "last_update" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text") NOT NULL
);


ALTER TABLE "public"."bike_park_details" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."bikepark_clicks" (
    "bikepark_id" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "id" bigint NOT NULL
);


ALTER TABLE "public"."bikepark_clicks" OWNER TO "postgres";


COMMENT ON TABLE "public"."bikepark_clicks" IS 'This is a duplicate of dirtpark_clicks';



ALTER TABLE "public"."bikepark_clicks" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."bikepark_clicks_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."dirt_park_details" (
    "id" "text" NOT NULL,
    "status" "text",
    "status_hint" "text",
    "opening_hours" "text",
    "rules" "jsonb",
    "trails_descriptions" "jsonb",
    "last_update" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text") NOT NULL
);


ALTER TABLE "public"."dirt_park_details" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."dirt_parks" (
    "id" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" DEFAULT ''::"text" NOT NULL,
    "url" "text" DEFAULT ''::"text",
    "instagram" "text" DEFAULT ''::"text",
    "latitude" real NOT NULL,
    "longitude" real NOT NULL,
    "approved" boolean DEFAULT false NOT NULL,
    "creator" "text",
    "pumptrack" boolean DEFAULT false,
    "dirtpark" boolean DEFAULT false,
    "creator_id" "uuid"
);


ALTER TABLE "public"."dirt_parks" OWNER TO "postgres";


COMMENT ON TABLE "public"."dirt_parks" IS 'dirt parks and pump tracks';



CREATE TABLE IF NOT EXISTS "public"."dirtpark_clicks" (
    "dirtpark_id" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "id" bigint NOT NULL
);


ALTER TABLE "public"."dirtpark_clicks" OWNER TO "postgres";


ALTER TABLE "public"."dirtpark_clicks" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."dirtpark_clicks_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."parks" (
    "id" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" DEFAULT ''::"text" NOT NULL,
    "url" "text" DEFAULT ''::"text",
    "instagram" "text" DEFAULT ''::"text",
    "latitude" real NOT NULL,
    "longitude" real NOT NULL,
    "approved" boolean DEFAULT false NOT NULL,
    "creator" "text",
    "creator_id" "uuid"
);


ALTER TABLE "public"."parks" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."profiles" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "display_name" "text",
    "avatar_url" "text"
);


ALTER TABLE "public"."profiles" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."spot_gpx_tours" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "spot_id" "text" NOT NULL,
    "filename" "text",
    "name" "text" NOT NULL,
    "direction" "text" NOT NULL,
    "trail_names" "jsonb",
    "distance_km" real,
    "elevation_gain" integer,
    "elevation_loss" integer,
    "duration_minutes" integer,
    "gpx_points" "jsonb" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "gpx_url" "text"
);


ALTER TABLE "public"."spot_gpx_tours" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."spot_gpx_trails" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "spot_id" "text" NOT NULL,
    "filename" "text",
    "name" "text" NOT NULL,
    "difficulty" "text" NOT NULL,
    "direction" "text" NOT NULL,
    "distance_km" real,
    "elevation_gain" integer,
    "elevation_loss" integer,
    "duration_minutes" integer,
    "gpx_points" "jsonb" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "gpx_url" "text"
);


ALTER TABLE "public"."spot_gpx_trails" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."trail_clicks" (
    "trail_id" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "id" bigint NOT NULL
);


ALTER TABLE "public"."trail_clicks" OWNER TO "postgres";


ALTER TABLE "public"."trail_clicks" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."trail_clicks_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."trail_details_feedback" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "trail_id" "text",
    "up" boolean DEFAULT false NOT NULL
);


ALTER TABLE "public"."trail_details_feedback" OWNER TO "postgres";


ALTER TABLE "public"."trail_details_feedback" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."trail_detail_feedback_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."trail_details" (
    "trail_id" "text" NOT NULL,
    "status" "text",
    "status_hint" "text",
    "opening_hours_text" "text",
    "rules" "jsonb",
    "trail_description" "text",
    "last_update" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text") NOT NULL,
    "status_until" "date",
    "affected_trail_ids" "text"[] DEFAULT '{}'::"text"[] NOT NULL,
    "seasonal_from" "text",
    "seasonal_to" "text",
    "rain_policy" "text" DEFAULT 'none'::"text" NOT NULL,
    "rain_closed_hours" integer,
    "rain_window_from" "text",
    "rain_window_to" "text",
    "night_policy" "text" DEFAULT 'none'::"text" NOT NULL,
    "night_before_dusk_min" integer,
    "night_after_dawn_min" integer,
    "access_type" "text" DEFAULT 'free'::"text" NOT NULL,
    "donation_url" "text",
    CONSTRAINT "access_type_values" CHECK (("access_type" = ANY (ARRAY['free'::"text", 'paid'::"text", 'membership'::"text"]))),
    CONSTRAINT "night_policy_values" CHECK (("night_policy" = ANY (ARRAY['none'::"text", 'dusk_to_dawn'::"text", 'offset'::"text"]))),
    CONSTRAINT "rain_policy_values" CHECK (("rain_policy" = ANY (ARRAY['none'::"text", 'during'::"text", 'after'::"text"])))
);


ALTER TABLE "public"."trail_details" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."trail_favorites" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "trail_id" "text" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL
);


ALTER TABLE "public"."trail_favorites" OWNER TO "postgres";


ALTER TABLE "public"."trail_favorites" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."trail_favorites_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."trail_photos" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "trail_id" "text",
    "url" "text",
    "creator" "uuid"
);


ALTER TABLE "public"."trail_photos" OWNER TO "postgres";


ALTER TABLE "public"."trail_photos" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."trail_photos_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."trail_shares" (
    "trail_id" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "id" bigint NOT NULL
);


ALTER TABLE "public"."trail_shares" OWNER TO "postgres";


COMMENT ON TABLE "public"."trail_shares" IS 'This is a duplicate of trail_clicks';



ALTER TABLE "public"."trail_shares" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."trail_shares_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."trail_videos" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "trail_id" "text",
    "url" "text",
    "creator" "text"
);


ALTER TABLE "public"."trail_videos" OWNER TO "postgres";


COMMENT ON TABLE "public"."trail_videos" IS 'trail_videos';



ALTER TABLE "public"."trail_videos" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."trail_videos_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."trailcrew_spots" (
    "user_id" "uuid" NOT NULL,
    "spot_id" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."trailcrew_spots" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."trails" (
    "id" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" DEFAULT ''::"text" NOT NULL,
    "url" "text" DEFAULT ''::"text",
    "instagram" "text" DEFAULT ''::"text",
    "latitude" real NOT NULL,
    "longitude" real NOT NULL,
    "approved" boolean DEFAULT false NOT NULL,
    "creator" "text",
    "visible" boolean DEFAULT true NOT NULL,
    "creator_id" "uuid",
    "spotcheck" "text"
);


ALTER TABLE "public"."trails" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."user_roles" (
    "user_id" "uuid" NOT NULL,
    "role" "public"."user_role" DEFAULT 'user'::"public"."user_role" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."user_roles" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."visits" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_agent" "text",
    "mobile" boolean DEFAULT false,
    "platform" "text",
    "referrer" "text",
    "path" "text" DEFAULT '/'::"text"
);


ALTER TABLE "public"."visits" OWNER TO "postgres";


ALTER TABLE "public"."visits" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."visits_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."add_entry_aborts"
    ADD CONSTRAINT "add_entry_aborts_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."bike_park_details"
    ADD CONSTRAINT "bike_park_details_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."bikepark_clicks"
    ADD CONSTRAINT "bikepark_clicks_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."dirt_park_details"
    ADD CONSTRAINT "dirt_park_details_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."dirtpark_clicks"
    ADD CONSTRAINT "dirtpark_clicks_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."parks"
    ADD CONSTRAINT "parks_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."spot_gpx_tours"
    ADD CONSTRAINT "spot_gpx_tours_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."spot_gpx_tours"
    ADD CONSTRAINT "spot_gpx_tours_spot_id_filename_key" UNIQUE ("spot_id", "filename");



ALTER TABLE ONLY "public"."spot_gpx_trails"
    ADD CONSTRAINT "spot_gpx_trails_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."spot_gpx_trails"
    ADD CONSTRAINT "spot_gpx_trails_spot_id_filename_key" UNIQUE ("spot_id", "filename");



ALTER TABLE ONLY "public"."trail_clicks"
    ADD CONSTRAINT "trail_clicks_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."trail_details_feedback"
    ADD CONSTRAINT "trail_detail_feedback_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."trail_details"
    ADD CONSTRAINT "trail_details_pkey" PRIMARY KEY ("trail_id");



ALTER TABLE ONLY "public"."trail_favorites"
    ADD CONSTRAINT "trail_favorites_pkey" PRIMARY KEY ("trail_id", "user_id");



ALTER TABLE ONLY "public"."trail_photos"
    ADD CONSTRAINT "trail_photos_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."trail_shares"
    ADD CONSTRAINT "trail_shares_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."trail_videos"
    ADD CONSTRAINT "trail_videos_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."trailcrew_spots"
    ADD CONSTRAINT "trailcrew_spots_pkey" PRIMARY KEY ("user_id", "spot_id");



ALTER TABLE ONLY "public"."dirt_parks"
    ADD CONSTRAINT "trails_duplicate_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."trails"
    ADD CONSTRAINT "trails_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."user_roles"
    ADD CONSTRAINT "user_roles_pkey" PRIMARY KEY ("user_id");



ALTER TABLE ONLY "public"."visits"
    ADD CONSTRAINT "visits_pkey" PRIMARY KEY ("id");



CREATE INDEX "spot_gpx_tours_spot_id" ON "public"."spot_gpx_tours" USING "btree" ("spot_id");



CREATE INDEX "spot_gpx_trails_spot_id" ON "public"."spot_gpx_trails" USING "btree" ("spot_id");



CREATE OR REPLACE TRIGGER "handle_last_update" BEFORE UPDATE ON "public"."trail_details" FOR EACH ROW EXECUTE FUNCTION "public"."moddatetime"('last_update');



ALTER TABLE ONLY "public"."bike_park_details"
    ADD CONSTRAINT "bike_park_details_id_fkey" FOREIGN KEY ("id") REFERENCES "public"."parks"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."bikepark_clicks"
    ADD CONSTRAINT "bikepark_clicks_bikepark_id_fkey" FOREIGN KEY ("bikepark_id") REFERENCES "public"."parks"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."dirt_park_details"
    ADD CONSTRAINT "dirt_park_details_id_fkey" FOREIGN KEY ("id") REFERENCES "public"."dirt_parks"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."dirt_parks"
    ADD CONSTRAINT "dirt_parks_creator_id_fkey" FOREIGN KEY ("creator_id") REFERENCES "auth"."users"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."dirtpark_clicks"
    ADD CONSTRAINT "dirtpark_clicks_dirtpark_id_fkey" FOREIGN KEY ("dirtpark_id") REFERENCES "public"."dirt_parks"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."parks"
    ADD CONSTRAINT "parks_creator_id_fkey" FOREIGN KEY ("creator_id") REFERENCES "auth"."users"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."trail_clicks"
    ADD CONSTRAINT "trail_clicks_trail_id_fkey" FOREIGN KEY ("trail_id") REFERENCES "public"."trails"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."trail_details_feedback"
    ADD CONSTRAINT "trail_detail_feedback_trail_id_fkey" FOREIGN KEY ("trail_id") REFERENCES "public"."trails"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."trail_details"
    ADD CONSTRAINT "trail_details_trail_id_fkey" FOREIGN KEY ("trail_id") REFERENCES "public"."trails"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."trail_favorites"
    ADD CONSTRAINT "trail_favorites_trail_id_fkey" FOREIGN KEY ("trail_id") REFERENCES "public"."trails"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."trail_favorites"
    ADD CONSTRAINT "trail_favorites_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."trail_photos"
    ADD CONSTRAINT "trail_photos_creator_fkey" FOREIGN KEY ("creator") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."trail_photos"
    ADD CONSTRAINT "trail_photos_creator_fkey1" FOREIGN KEY ("creator") REFERENCES "public"."profiles"("id");



ALTER TABLE ONLY "public"."trail_photos"
    ADD CONSTRAINT "trail_photos_trail_id_fkey" FOREIGN KEY ("trail_id") REFERENCES "public"."trails"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."trail_shares"
    ADD CONSTRAINT "trail_shares_trail_id_fkey" FOREIGN KEY ("trail_id") REFERENCES "public"."trails"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."trail_videos"
    ADD CONSTRAINT "trail_videos_trail_id_fkey" FOREIGN KEY ("trail_id") REFERENCES "public"."trails"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."trail_videos"
    ADD CONSTRAINT "trail_videos_trail_id_fkey1" FOREIGN KEY ("trail_id") REFERENCES "public"."trail_details"("trail_id");



ALTER TABLE ONLY "public"."trailcrew_spots"
    ADD CONSTRAINT "trailcrew_spots_spot_id_fkey" FOREIGN KEY ("spot_id") REFERENCES "public"."trails"("id");



ALTER TABLE ONLY "public"."trailcrew_spots"
    ADD CONSTRAINT "trailcrew_spots_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."trails"
    ADD CONSTRAINT "trails_creator_id_fkey" FOREIGN KEY ("creator_id") REFERENCES "auth"."users"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."user_roles"
    ADD CONSTRAINT "user_roles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



CREATE POLICY "Enable insert for authenticated users only" ON "public"."trails" FOR INSERT TO "anon", "service_role" WITH CHECK (true);



CREATE POLICY "Enable insert for users based on user_id" ON "public"."trail_favorites" FOR INSERT WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "user_id"));



CREATE POLICY "add dirt park details" ON "public"."dirt_park_details" FOR INSERT TO "anon" WITH CHECK (true);



CREATE POLICY "add entry creation abort" ON "public"."add_entry_aborts" FOR INSERT TO "anon" WITH CHECK (true);



CREATE POLICY "add feedback" ON "public"."trail_details_feedback" FOR INSERT TO "anon" WITH CHECK (true);



CREATE POLICY "add parks" ON "public"."dirt_parks" FOR INSERT TO "anon" WITH CHECK (true);



CREATE POLICY "add trail click" ON "public"."trail_clicks" FOR INSERT TO "anon", "service_role" WITH CHECK (true);



ALTER TABLE "public"."add_entry_aborts" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "admins manage roles" ON "public"."user_roles" USING ("public"."is_admin"());



CREATE POLICY "admins manage scopes" ON "public"."trailcrew_spots" TO "authenticated" USING ("public"."is_admin"());



ALTER TABLE "public"."bike_park_details" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."bikepark_clicks" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "delete" ON "public"."trail_favorites" FOR DELETE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "user_id"));



CREATE POLICY "delete admin only" ON "public"."spot_gpx_tours" FOR DELETE TO "authenticated", "service_role" USING ("public"."is_admin"());



CREATE POLICY "delete admin only" ON "public"."spot_gpx_trails" FOR DELETE TO "authenticated", "service_role" USING ("public"."is_admin"());



ALTER TABLE "public"."dirt_park_details" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."dirt_parks" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."dirtpark_clicks" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "edit own scope" ON "public"."spot_gpx_tours" FOR UPDATE TO "authenticated", "service_role" USING ("public"."can_edit_spot"("spot_id"));



CREATE POLICY "edit own scope" ON "public"."spot_gpx_trails" FOR UPDATE TO "authenticated", "service_role" USING ("public"."can_edit_spot"("spot_id"));



CREATE POLICY "get" ON "public"."bike_park_details" FOR SELECT TO "anon" USING (true);



CREATE POLICY "get" ON "public"."profiles" FOR SELECT TO "anon" USING (true);



CREATE POLICY "get" ON "public"."trail_favorites" FOR SELECT TO "authenticated", "anon" USING (true);



CREATE POLICY "get" ON "public"."trail_photos" FOR SELECT TO "anon" USING (true);



CREATE POLICY "get" ON "public"."trail_videos" FOR SELECT TO "anon" USING (true);



CREATE POLICY "get details" ON "public"."dirt_park_details" FOR SELECT TO "anon" USING (true);



CREATE POLICY "get details" ON "public"."trail_details" FOR SELECT TO "authenticated", "anon" USING (true);



CREATE POLICY "get parks" ON "public"."dirt_parks" FOR SELECT TO "anon" USING (true);



CREATE POLICY "get trails" ON "public"."trails" FOR SELECT TO "authenticated", "anon", "service_role" USING (true);



CREATE POLICY "insert" ON "public"."bikepark_clicks" FOR INSERT TO "anon", "service_role" WITH CHECK (true);



CREATE POLICY "insert" ON "public"."dirtpark_clicks" FOR INSERT TO "anon", "service_role" WITH CHECK (true);



CREATE POLICY "insert" ON "public"."parks" FOR INSERT TO "anon", "service_role" WITH CHECK (true);



CREATE POLICY "insert" ON "public"."trail_photos" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "insert" ON "public"."trail_shares" FOR INSERT WITH CHECK (true);



CREATE POLICY "insert details" ON "public"."trail_details" FOR INSERT TO "authenticated", "service_role" WITH CHECK ("public"."can_edit_spot"("trail_id"));



CREATE POLICY "insert own scope" ON "public"."spot_gpx_tours" FOR INSERT TO "authenticated" WITH CHECK ("public"."can_edit_spot"("spot_id"));



CREATE POLICY "insert own scope" ON "public"."spot_gpx_trails" FOR INSERT TO "authenticated" WITH CHECK ("public"."can_edit_spot"("spot_id"));



CREATE POLICY "insertpublic" ON "public"."visits" FOR INSERT TO "anon", "service_role" WITH CHECK (true);



ALTER TABLE "public"."parks" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."profiles" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "public read tours" ON "public"."spot_gpx_tours" FOR SELECT USING (true);



CREATE POLICY "public read trails" ON "public"."spot_gpx_trails" FOR SELECT USING (true);



CREATE POLICY "select" ON "public"."parks" FOR SELECT TO "anon", "service_role" USING (true);



CREATE POLICY "set" ON "public"."bike_park_details" FOR INSERT TO "anon" WITH CHECK (true);



ALTER TABLE "public"."spot_gpx_tours" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."spot_gpx_trails" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."trail_clicks" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."trail_details" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."trail_details_feedback" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."trail_favorites" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."trail_photos" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."trail_shares" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."trail_videos" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "trailcrew reads own" ON "public"."trailcrew_spots" FOR SELECT USING (("user_id" = "auth"."uid"()));



ALTER TABLE "public"."trailcrew_spots" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."trails" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "update" ON "public"."bike_park_details" FOR UPDATE TO "anon" USING (true);



CREATE POLICY "update" ON "public"."dirt_park_details" FOR UPDATE TO "anon" USING (true);



CREATE POLICY "update" ON "public"."trail_details" FOR UPDATE TO "authenticated", "service_role" USING ("public"."can_edit_spot"("trail_id"));



ALTER TABLE "public"."user_roles" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "users read own role" ON "public"."user_roles" FOR SELECT USING (("user_id" = "auth"."uid"()));



ALTER TABLE "public"."visits" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";


























































































































































































GRANT ALL ON FUNCTION "public"."can_edit_spot"("p_spot_id" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."can_edit_spot"("p_spot_id" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."can_edit_spot"("p_spot_id" "text") TO "service_role";



GRANT ALL ON FUNCTION "public"."get_my_role"() TO "anon";
GRANT ALL ON FUNCTION "public"."get_my_role"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_my_role"() TO "service_role";



GRANT ALL ON FUNCTION "public"."is_admin"() TO "anon";
GRANT ALL ON FUNCTION "public"."is_admin"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."is_admin"() TO "service_role";



GRANT ALL ON FUNCTION "public"."moddatetime"() TO "postgres";
GRANT ALL ON FUNCTION "public"."moddatetime"() TO "anon";
GRANT ALL ON FUNCTION "public"."moddatetime"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."moddatetime"() TO "service_role";



GRANT ALL ON FUNCTION "public"."sync_profile_from_auth_users"() TO "anon";
GRANT ALL ON FUNCTION "public"."sync_profile_from_auth_users"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."sync_profile_from_auth_users"() TO "service_role";
























GRANT ALL ON TABLE "public"."add_entry_aborts" TO "anon";
GRANT ALL ON TABLE "public"."add_entry_aborts" TO "authenticated";
GRANT ALL ON TABLE "public"."add_entry_aborts" TO "service_role";



GRANT ALL ON SEQUENCE "public"."add_entry_aborts_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."add_entry_aborts_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."add_entry_aborts_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."bike_park_details" TO "anon";
GRANT ALL ON TABLE "public"."bike_park_details" TO "authenticated";
GRANT ALL ON TABLE "public"."bike_park_details" TO "service_role";



GRANT ALL ON TABLE "public"."bikepark_clicks" TO "anon";
GRANT ALL ON TABLE "public"."bikepark_clicks" TO "authenticated";
GRANT ALL ON TABLE "public"."bikepark_clicks" TO "service_role";



GRANT ALL ON SEQUENCE "public"."bikepark_clicks_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."bikepark_clicks_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."bikepark_clicks_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."dirt_park_details" TO "anon";
GRANT ALL ON TABLE "public"."dirt_park_details" TO "authenticated";
GRANT ALL ON TABLE "public"."dirt_park_details" TO "service_role";



GRANT ALL ON TABLE "public"."dirt_parks" TO "anon";
GRANT ALL ON TABLE "public"."dirt_parks" TO "authenticated";
GRANT ALL ON TABLE "public"."dirt_parks" TO "service_role";



GRANT ALL ON TABLE "public"."dirtpark_clicks" TO "anon";
GRANT ALL ON TABLE "public"."dirtpark_clicks" TO "authenticated";
GRANT ALL ON TABLE "public"."dirtpark_clicks" TO "service_role";



GRANT ALL ON SEQUENCE "public"."dirtpark_clicks_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."dirtpark_clicks_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."dirtpark_clicks_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."parks" TO "anon";
GRANT ALL ON TABLE "public"."parks" TO "authenticated";
GRANT ALL ON TABLE "public"."parks" TO "service_role";



GRANT ALL ON TABLE "public"."profiles" TO "anon";
GRANT ALL ON TABLE "public"."profiles" TO "authenticated";
GRANT ALL ON TABLE "public"."profiles" TO "service_role";



GRANT ALL ON TABLE "public"."spot_gpx_tours" TO "anon";
GRANT ALL ON TABLE "public"."spot_gpx_tours" TO "authenticated";
GRANT ALL ON TABLE "public"."spot_gpx_tours" TO "service_role";



GRANT ALL ON TABLE "public"."spot_gpx_trails" TO "anon";
GRANT ALL ON TABLE "public"."spot_gpx_trails" TO "authenticated";
GRANT ALL ON TABLE "public"."spot_gpx_trails" TO "service_role";



GRANT ALL ON TABLE "public"."trail_clicks" TO "anon";
GRANT ALL ON TABLE "public"."trail_clicks" TO "authenticated";
GRANT ALL ON TABLE "public"."trail_clicks" TO "service_role";



GRANT ALL ON SEQUENCE "public"."trail_clicks_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."trail_clicks_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."trail_clicks_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."trail_details_feedback" TO "anon";
GRANT ALL ON TABLE "public"."trail_details_feedback" TO "authenticated";
GRANT ALL ON TABLE "public"."trail_details_feedback" TO "service_role";



GRANT ALL ON SEQUENCE "public"."trail_detail_feedback_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."trail_detail_feedback_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."trail_detail_feedback_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."trail_details" TO "anon";
GRANT ALL ON TABLE "public"."trail_details" TO "authenticated";
GRANT ALL ON TABLE "public"."trail_details" TO "service_role";



GRANT ALL ON TABLE "public"."trail_favorites" TO "anon";
GRANT ALL ON TABLE "public"."trail_favorites" TO "authenticated";
GRANT ALL ON TABLE "public"."trail_favorites" TO "service_role";



GRANT ALL ON SEQUENCE "public"."trail_favorites_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."trail_favorites_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."trail_favorites_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."trail_photos" TO "anon";
GRANT ALL ON TABLE "public"."trail_photos" TO "authenticated";
GRANT ALL ON TABLE "public"."trail_photos" TO "service_role";



GRANT ALL ON SEQUENCE "public"."trail_photos_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."trail_photos_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."trail_photos_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."trail_shares" TO "anon";
GRANT ALL ON TABLE "public"."trail_shares" TO "authenticated";
GRANT ALL ON TABLE "public"."trail_shares" TO "service_role";



GRANT ALL ON SEQUENCE "public"."trail_shares_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."trail_shares_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."trail_shares_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."trail_videos" TO "anon";
GRANT ALL ON TABLE "public"."trail_videos" TO "authenticated";
GRANT ALL ON TABLE "public"."trail_videos" TO "service_role";



GRANT ALL ON SEQUENCE "public"."trail_videos_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."trail_videos_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."trail_videos_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."trailcrew_spots" TO "anon";
GRANT ALL ON TABLE "public"."trailcrew_spots" TO "authenticated";
GRANT ALL ON TABLE "public"."trailcrew_spots" TO "service_role";



GRANT ALL ON TABLE "public"."trails" TO "anon";
GRANT ALL ON TABLE "public"."trails" TO "authenticated";
GRANT ALL ON TABLE "public"."trails" TO "service_role";



GRANT ALL ON TABLE "public"."user_roles" TO "anon";
GRANT ALL ON TABLE "public"."user_roles" TO "authenticated";
GRANT ALL ON TABLE "public"."user_roles" TO "service_role";



GRANT ALL ON TABLE "public"."visits" TO "anon";
GRANT ALL ON TABLE "public"."visits" TO "authenticated";
GRANT ALL ON TABLE "public"."visits" TO "service_role";



GRANT ALL ON SEQUENCE "public"."visits_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."visits_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."visits_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































drop extension if exists "pg_net";

drop policy "insert" on "public"."bikepark_clicks";

drop policy "insert" on "public"."dirtpark_clicks";

drop policy "get details" on "public"."trail_details";

drop policy "get" on "public"."trail_favorites";

drop policy "get trails" on "public"."trails";

drop policy "insertpublic" on "public"."visits";


  create policy "insert"
  on "public"."bikepark_clicks"
  as permissive
  for insert
  to service_role, anon
with check (true);



  create policy "insert"
  on "public"."dirtpark_clicks"
  as permissive
  for insert
  to service_role, anon
with check (true);



  create policy "get details"
  on "public"."trail_details"
  as permissive
  for select
  to anon, authenticated
using (true);



  create policy "get"
  on "public"."trail_favorites"
  as permissive
  for select
  to anon, authenticated
using (true);



  create policy "get trails"
  on "public"."trails"
  as permissive
  for select
  to anon, service_role, authenticated
using (true);



  create policy "insertpublic"
  on "public"."visits"
  as permissive
  for insert
  to service_role, anon
with check (true);


CREATE TRIGGER sync_profile AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.sync_profile_from_auth_users();

CREATE TRIGGER sync_profile_trigger AFTER INSERT OR UPDATE ON auth.users FOR EACH ROW EXECUTE FUNCTION public.sync_profile_from_auth_users();


  create policy "Give users access to avatars 1oj01fe_0"
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'avatars'::text));



  create policy "Give users access to own folder  fp0rfd_0"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check ((((bucket_id = 'gpx-files'::text) AND public.is_admin()) OR ((public.get_my_role() = 'trailcrew'::public.user_role) AND (EXISTS ( SELECT 1
   FROM public.trailcrew_spots
  WHERE ((trailcrew_spots.user_id = auth.uid()) AND (trailcrew_spots.spot_id = lower((storage.foldername(objects.name))[1]))))))));



  create policy "Give users access to own folder  fp0rfd_1"
  on "storage"."objects"
  as permissive
  for update
  to authenticated
using (((bucket_id = 'gpx-files'::text) AND public.is_admin()));



  create policy "Give users access to own folder  fp0rfd_3"
  on "storage"."objects"
  as permissive
  for delete
  to authenticated
using (((bucket_id = 'gpx-files'::text) AND public.is_admin()));



  create policy "User can update own avatar 1oj01fe_0"
  on "storage"."objects"
  as permissive
  for update
  to public
using ((((bucket_id = 'avatars'::text) AND (owner_id = (auth.uid())::text)) OR (owner_id IS NULL)));



  create policy "User can update own avatar 1oj01fe_1"
  on "storage"."objects"
  as permissive
  for select
  to public
using (((bucket_id = 'avatars'::text) AND ((auth.uid())::text = split_part(name, '/'::text, 1))));



  create policy "User can upload own avatar 1oj01fe_0"
  on "storage"."objects"
  as permissive
  for insert
  to public
with check (((bucket_id = 'avatars'::text) AND (auth.uid() IS NOT NULL)));



  create policy "upload trail photos 43bqjs_0"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check ((bucket_id = 'trail-photos'::text));



